spring:
  application:
    name: user-service  # Service name for Eureka registration
server:
  port: 8081           # Unique port for user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL